# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rb_sys/extensiontask'

task build: :compile

GEMSPEC = Gem::Specification.load('gem_error_codes.gemspec')

RbSys::ExtensionTask.new('gem_error_codes', GEMSPEC) do |ext|
  ext.lib_dir = 'lib/gem_error_codes'
end

task default: :compile
